[model]
dim = 4096
n_vocab = 32000
hf_model_id = "mistralai/Mixtral-8x7B-Instruct-v0.1"
pad_token = "</s>"

[tokenizer]
return_tensors = "pt"
return_attention_mask = true
max_length = 128
padding = "max_length"
truncation = true
add_special_tokens = false

[training]
output_dir = "output/matryoshka_mixtral"
num_train_epochs = 2
per_device_train_batch_size = 512
warmup_steps = 256
evaluation_strategy = "steps"
eval_steps = 250
save_steps = 1000
fp16 = true
include_num_input_tokens_seen = false
learning_rate = 5e-4
multi_dataset_batch_sampler = "PROPORTIONAL"
binarizer_ste = "tanh"

[matryoshka]
dims = [1024, 512, 256, 128, 64]

